Fix issue with agent name parameter
damies13/rfswarm pull request #99
Opened 2022-01-07 14:32 UTC by vaistomarkus

Currently the -a or --agentname option for rfswarm-agent is not updating the actual agent name in the manager. This PR addresses that issue.

If agent name is now passed as a parameter it will override the value in the .ini file. If there is no parameter passed the value will be read from the .ini file. If the value doesn't exist in the .ini file already, the agent machine hostname is first written to the .ini file.

2022-01-10 22:52 UTC, damies13 requested changes
Thank you for your bug fix, please resubmit on a branch with the issue number so I can include in the next release
Also thanks for making me realise I haven't created the documentation for how to contribute to this project yet.
Just as an FYI, I never commit to master (except documentation changes) all fixed are committed to a branch for their issue, then the fix branch merged into a release branch when ready, only release branch is merged to master when on release day.

2022-01-10 22:59 UTC, damies13 commented
Hi @vaistomarkus 

This is not actually a bug, this is by design, see the documentation, [first line of command line interface](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_agent_py.md#command-line-interface) mentions that "These command line options allow you to override the ini file configuration ___but do not update the ini file___."

The intention is if you want the change permanent you update the ini file with a text editor, the command line option allows a one time or temporary change.

Happy to discuss.

2022-01-11 07:35 UTC, vaistomarkus commented
Hi @damies13 Oopsies, I think you already mentioned about not submitting to the master branch in your contributing file. Sorry about that.

Really my original issue was that the command line parameter for the agent name didn't actually change the name for that test run. Currently the code first does this:

```python
self.agentname = socket.gethostname()
   if self.args.agentname:
   self.agentname = self.args.agentname
```

And this to me seems fine, if the parameter is given, it will be set as a variable for the class. However then later there's this block:

```python
if 'agentname' not in self.config['Agent']:
    self.config['Agent']['agentname'] = self.agentname
    self.saveini()
else:
    self.agentname = self.config['Agent']['agentname']
```

So there it actually does update the ini file if agentname doesn't already exist there. Otherwise, (which I guess is almost all of the cases) it uses the value already present in the ini file ignoring the given parameter.

In my change, it first checks if the argument is given and updates that to be the instance variable.
```python
if self.args.agentname:
    self.agentname = self.args.agentname
```

And then it checks if there's a value for the agentname in ini file. If there isn't, it only then sets that to be the hostname, which to me seems like a reasonable behavior. Lastly it checks if the agent name was given as a parameter and if not it then uses the value in the ini file. The value in the ini file at that point holds either the value that was already there or the hostname that was just updated to it.

```python
   if 'agentname' not in self.config['Agent']:
        self.config['Agent']['agentname'] = socket.gethostname()
        self.saveini()

    if not self.args.agentname:
        self.agentname = self.config['Agent']['agentname']
```

In my mind this would now match the documented behavior. Let me know what you think, I can open a new issue if needed ☺️

2022-01-12 23:30 UTC, damies13 commented
Hi @vaistomarkus ,
I think I may have misread your original issue as you were expecting the the command line option to update the ini file, I see my misunderstanding now.

Ok A little table to help me understand what is happening 

| |Original code ||This PR||
|--|--|--|--|--|
| |1st run|2nd+ run|1st run|2nd+ run|
|default |hostname | ini setting |hostname | ini setting|
|-a or --agentname | -a value| ini setting| -a value| -a value|

Yes I see now your change is what it should be, thanks, I wrote this code nearly 2 years ago, and hadn't found this issue yet, so good pick up.

If you can push as a branch I'll add it to the next release.

Thanks,
Dave.

2022-01-13 11:58 UTC, vaistomarkus commented
Hi @damies13,

It's very understandable to have small bugs like this to be present without noticing!

I added a new issue https://github.com/damies13/rfswarm/issues/100, made a corresponding branch and created a new pull request https://github.com/damies13/rfswarm/pull/101. I assume the branch v.0.9.0 is the one it should be merged to but of course that can still be changed if needed. I think everything is now correctly done, please let me know if I still screwed something up 😄

Rfswarm has worked really for my current testing needs, thank you for that 😊 Have a great day and rest of the week!

-Markus

2022-02-04 03:24 UTC, damies13 commented
pull request https://github.com/damies13/rfswarm/pull/101 merged into branch v.0.9.0

2022-02-04 03:24 UTC, closed without merging